connection pool
guillotinaweb/aiofluent pull request #4
Opened 2020-02-21 20:12 UTC by vjove

2020-02-21 22:45 UTC, vangheem requested changes
So this is like a round robin. Each emitted log will use a different conn from the pool in sequence?

Maybe we should have a lock on the connection itself? I guess it wouldn't be necessary because we're still only processing in a queue.

I also wonder now... It would probably be best to have a global pool. Right now, if you create 10 log handlers with with approach, you'll get 10 * size of your pool connections.

Finally, we need a way to configure the pool size from the handler object.

Thank you!

2020-02-21 22:45 UTC, vangheem commented on aiofluent/sender.py
> +                 size_pool_conn=1,
can we rename to `connection_pool_size`?

2020-02-21 22:45 UTC, vangheem commented on aiofluent/sender.py
>          async with self.lock:
Do we only need locks on a connection in the pool now?

2020-02-21 22:45 UTC, vangheem commented on aiofluent/sender.py
> +        self._size_pool_conn = size_pool_conn
rename to `_connection_pool_size`

2020-02-21 22:45 UTC, vangheem commented on aiofluent/sender.py
> +        self._pool_conn = []
`_connection_pool`

2020-02-21 22:45 UTC, vangheem commented on aiofluent/sender.py
> +            if len(self._pool_conn) == self._size_pool_conn:
Maybe just fill pool up with all the connections immediately and then just use `random.choice`? It would make the code more simple.

2020-10-09 06:07 UTC, vjove commented
Discarded PR.

2020-10-09 06:07 UTC, closed without merging